version: "3"

services:
  postgres:
    image: postgres
    container_name: meetapp-postgres
    restart: always
    ports:
      - 5532:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=meetapp
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: meetapp
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
